github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod


image:
  file: docker/biomart/Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:    
  - name: Download Nextflow Tutorial
    init: |
      echo 'init script' # runs during prebuild
      curl -s https://get.nextflow.io | bash
      #sudo apt install -y dirmngr gnupg apt-transport-https ca-certificates software-properties-common
      #sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
      #sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/'
      #sudo apt install -y r-base
      #sudo apt install -y build-essential
      #mkdir lib
      #chmod a+rwx lib
      #Rscript bin/install_biomart.R

    command: |
      export PATH=/workspace/Goatee:$PATH
      nextflow info
      unset JAVA_TOOL_OPTIONS
      echo 'Starting workspace !'
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000
